name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.14.15'

      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Execute the test suite
        uses: ./
        with:
          test-packages: 'test/smoke/basic/...'
